# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-07 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tblusers',
            fields=[
                ('userid', models.CharField(db_column='UserID', max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=50, null=True)),
                ('usergroup', models.CharField(blank=True, db_column='UserGroup', max_length=1, null=True)),
                ('plant', models.CharField(blank=True, db_column='Plant', max_length=10, null=True)),
                ('plantdetails', models.CharField(blank=True, db_column='PlantDetails', max_length=100, null=True)),
                ('employeeid', models.CharField(blank=True, db_column='EmployeeID', max_length=50, null=True)),
                ('prefixt', models.CharField(blank=True, db_column='PrefixT', max_length=20, null=True)),
                ('firstnamet', models.CharField(blank=True, db_column='FirstNameT', max_length=20, null=True)),
                ('lastnamet', models.CharField(blank=True, db_column='LastNameT', max_length=30, null=True)),
                ('prefixe', models.CharField(blank=True, db_column='PrefixE', max_length=20, null=True)),
                ('firstnamee', models.CharField(blank=True, db_column='FirstNameE', max_length=20, null=True)),
                ('lastnamee', models.CharField(blank=True, db_column='LastNameE', max_length=30, null=True)),
                ('hiredate', models.DateTimeField(blank=True, db_column='HireDate', null=True)),
                ('positions', models.CharField(blank=True, db_column='Positions', max_length=50, null=True)),
                ('userlevel', models.CharField(blank=True, db_column='UserLevel', max_length=50, null=True)),
                ('usergrade', models.CharField(blank=True, db_column='UserGrade', max_length=50, null=True)),
                ('worktype', models.CharField(blank=True, db_column='WorkType', max_length=1, null=True)),
                ('opstype', models.CharField(blank=True, db_column='OPSType', max_length=2, null=True)),
                ('department', models.CharField(blank=True, db_column='Department', max_length=200, null=True)),
                ('sex', models.CharField(blank=True, db_column='Sex', max_length=1, null=True)),
                ('maritalstatus', models.CharField(blank=True, db_column='MaritalStatus', max_length=1, null=True)),
                ('probativedate', models.DateTimeField(blank=True, db_column='ProbativeDate', null=True)),
                ('vacationdate', models.DateTimeField(blank=True, db_column='VacationDate', null=True)),
                ('vocation', models.FloatField(blank=True, db_column='Vocation', null=True)),
                ('vocationplus', models.FloatField(blank=True, db_column='VocationPlus', null=True)),
                ('vocationuse', models.FloatField(blank=True, db_column='VocationUse', null=True)),
                ('approver1', models.CharField(blank=True, db_column='Approver1', max_length=50, null=True)),
                ('approver2', models.CharField(blank=True, db_column='Approver2', max_length=50, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=50, null=True)),
                ('telphone', models.CharField(blank=True, db_column='Telphone', max_length=50, null=True)),
                ('loginflag', models.CharField(blank=True, db_column='LoginFlag', max_length=1, null=True)),
                ('logindate', models.DateTimeField(blank=True, db_column='LoginDate', null=True)),
                ('logoutdate', models.DateTimeField(blank=True, db_column='LogoutDate', null=True)),
                ('createuser', models.CharField(blank=True, db_column='CreateUser', max_length=20, null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
                ('lastedituser', models.CharField(blank=True, db_column='LastEditUser', max_length=20, null=True)),
                ('lasteditdate', models.DateTimeField(blank=True, db_column='LastEditDate', null=True)),
            ],
            options={
                'db_table': 'tblUsers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='File_Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=20, null=True)),
                ('file_path', models.CharField(blank=True, max_length=30, null=True)),
                ('upload_date', models.CharField(blank=True, max_length=25, null=True)),
                ('customer', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('first_demand_date', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forecast_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('version', models.CharField(blank=True, max_length=25, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('file_upload', models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='File_Upload_forecast', to='forecast.File_Upload')),
                ('forecast', models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Forecast_detail', to='forecast.Forecast')),
            ],
        ),
        migrations.CreateModel(
            name='User_Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(blank=True, max_length=10, null=True)),
                ('firstnamee', models.CharField(blank=True, max_length=20, null=True)),
                ('lastnamee', models.CharField(blank=True, max_length=30, null=True)),
                ('customer', models.CharField(blank=True, max_length=1024, null=True)),
                ('lastlogin', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='forecast',
            name='user',
            field=models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_Forecast_Forecast', to='forecast.User_Forecast'),
        ),
        migrations.AddField(
            model_name='file_upload',
            name='upload_by',
            field=models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_Forecast_File', to='forecast.User_Forecast'),
        ),
    ]
