# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-08 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='last_version',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
