# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-08 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0003_auto_20190108_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='file_upload',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
