# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-11 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0006_auto_20190111_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_file_temp',
            name='user',
            field=models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_Forecast_temp', to='forecast.User_Forecast'),
        ),
    ]
