# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-11 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0007_upload_file_temp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast_detail',
            name='work_week',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
