# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-16 08:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0008_forecast_detail_work_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast_detail',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
