# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-12 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0010_auto_20190204_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type_file',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
