# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-20 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0014_auto_20190220_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast_detail',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
