# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-15 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0017_forecast_svi_customer_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast_detail_svi',
            name='file_upload',
            field=models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='File_Upload_forecast_svi', to='forecast.File_Upload_Svi'),
        ),
        migrations.AlterField(
            model_name='forecast_svi',
            name='customer_version',
            field=models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_upload', to='forecast.File_Upload_Svi'),
        ),
        migrations.AlterField(
            model_name='upload_file_temp_svi',
            name='file_upload',
            field=models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='File_Upload_temp_svi', to='forecast.File_Upload_Svi'),
        ),
    ]
