# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-18 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0018_auto_20190315_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_upload_svi',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='file_upload_svi',
            name='upload_by',
        ),
        migrations.RemoveField(
            model_name='forecast_detail_svi',
            name='file_upload',
        ),
        migrations.RemoveField(
            model_name='forecast_detail_svi',
            name='forecast',
        ),
        migrations.RemoveField(
            model_name='forecast_svi',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='forecast_svi',
            name='customer_version',
        ),
        migrations.RemoveField(
            model_name='forecast_svi',
            name='user',
        ),
        migrations.RemoveField(
            model_name='upload_file_temp_svi',
            name='file_upload',
        ),
        migrations.RemoveField(
            model_name='upload_file_temp_svi',
            name='user',
        ),
        migrations.DeleteModel(
            name='File_Upload_Svi',
        ),
        migrations.DeleteModel(
            name='Forecast_Detail_svi',
        ),
        migrations.DeleteModel(
            name='Forecast_svi',
        ),
        migrations.DeleteModel(
            name='Upload_file_temp_svi',
        ),
    ]
