# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-21 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0020_forecast_detail_svi_forecast_svi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecast_detail_svi',
            old_name='status',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='forecast_svi',
            old_name='first_demand_date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='forecast_svi',
            old_name='last_version',
            new_name='last_update',
        ),
        migrations.RemoveField(
            model_name='forecast_detail_svi',
            name='file_upload',
        ),
        migrations.RemoveField(
            model_name='forecast_detail_svi',
            name='version',
        ),
        migrations.RemoveField(
            model_name='forecast_detail_svi',
            name='work_week',
        ),
        migrations.RemoveField(
            model_name='forecast_detail_svi',
            name='year',
        ),
        migrations.RemoveField(
            model_name='forecast_svi',
            name='description',
        ),
        migrations.RemoveField(
            model_name='forecast_svi',
            name='product_id',
        ),
        migrations.AddField(
            model_name='forecast_svi',
            name='file_upload',
            field=models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='File_Upload_forecast_svi', to='forecast.File_Upload'),
        ),
        migrations.AlterField(
            model_name='forecast_detail_svi',
            name='forecast',
            field=models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Forecast_detail_svi', to='forecast.Forecast_svi'),
        ),
    ]
