# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-22 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0021_auto_20190321_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast_svi',
            name='status',
            field=models.CharField(blank=True, default='Private', max_length=10, null=True),
        ),
    ]
