# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-25 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0022_forecast_svi_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast_detail_svi',
            name='old_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecast_detail_svi',
            name='old_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
