# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-25 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0023_auto_20190325_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast_detail_svi',
            name='old_date',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
